[package]
name = "zigbee"
version = "0.0.1"
edition = "2021"
default-run = "rx"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rx"
path = "src/bin/rx.rs"

[[bin]]
name = "trx"
path = "src/bin/trx.rs"

[[bin]]
name = "tx"
path = "src/bin/tx.rs"

[[bin]]
name = "aaronia"
path = "src/bin/aaronia.rs"
required-features = ["aaronia"]

[features]
default = []
aaronia = ["futuresdr/aaronia"]

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4.0.19", features = ["derive"] }
futuresdr = { path = "../..", features = ["soapy"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
futuresdr = { path = "../.." }
wasm-bindgen = "0.2.79"
wasm-bindgen-futures = "0.4.29"
