[package]
name = "buffer_rand"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
futuresdr = { path = "../..", features = ["flow_scheduler"] }
log = { version = "0.4", features = ["release_max_level_off"] }

[[bin]]
name = "buffer_rand"
path = "buffer_rand.rs"
