[package]
name = "msg"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
futuresdr = { path = "../.." }
log = { version = "0.4", features = ["release_max_level_off"] }

[[bin]]
name = "msg"
path = "msg.rs"
