[package]
name = "fir_latency"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
futuresdr = { path = "../..", features = ["flow_scheduler", "tpb_scheduler", "lttng"] }
log = { version = "0.4", features = ["release_max_level_off"] }
rand = "0.8.0"

[[bin]]
name = "fir"
path = "fir.rs"
