[package]
name = "rx-to-file"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
futuresdr = { path = "../..", features = ["soapy", "rtlsdr"] }
clap = { version = "4.0.19", features = ["derive"] }
