[package]
name = "wlan"
version = "0.1.0"
edition = "2021"
default-run = "loopback"

[workspace]

[[bin]]
name = "rx"
path = "src/bin/rx.rs"

[[bin]]
name = "loopback"
path = "src/bin/loopback.rs"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
crc32fast = "1.3.2"
futuresdr = { path = "../..", features = ["soapy"] }
futuredsp = { path = "../../futuredsp" }
