[package]
name = "spectrum"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cpu"
required-features = ["cpu"]

[[bin]]
name = "vulkan"
required-features = ["cpu", "vulkan"]

[features]
default = []
cpu = [ "futuresdr/soapy" ]
vulkan = [ "futuresdr/vulkan", "vulkano", "vulkano-shaders"]
wgpu = [ "futuresdr/wgpu" ]

[dependencies]
futuresdr = { path = "../.." }
vulkano = { version = "0.32.0", optional = true }
vulkano-shaders = { version = "0.32.0", optional = true }
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
